In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
## Movie Recommendation based on tags

# Creating DataFrame

In [2]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head(4)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
# Merging both the dataframes

In [5]:
movies = movies.merge(credits,on ='title')
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [ ]:
## Droping

In [45]:
# genres, movie_id, keywords, original_title, overview,cast, crew using these attributes we will create tags 
# with which we will recommend movies of similar tags

In [7]:
movies = movies[['movie_id','original_title','genres', 'keywords', 'overview','cast', 'crew']]
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Data Cleaning

## Removing Null Values

In [8]:
movies.isna().sum()

movie_id          0
original_title    0
genres            0
keywords          0
overview          3
cast              0
crew              0
dtype: int64

In [9]:
movies[movies['overview'].isna()]

,movie_id,original_title,genres,keywords,overview,cast,crew
2662,370980,Chiamatemi Francesco - Il Papa della gente,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 717, ""name"": ""pope""}, {""id"": 5565, ""na...",NaN,"[{""cast_id"": 5, ""character"": ""Jorge Mario Berg...","[{""credit_id"": ""5660019ac3a36875f100252b"", ""de..."
4147,459488,"To Be Frank, Sinatra at 100","[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 6027, ""name"": ""music""}, {""id"": 225822,...",NaN,"[{""cast_id"": 0, ""character"": ""Narrator"", ""cred...","[{""credit_id"": ""592b25e4c3a368783e065a2f"", ""de..."
4437,292539,Food Chains,"[{""id"": 99, ""name"": ""Documentary""}]",[],NaN,[],"[{""credit_id"": ""5470c3b1c3a368085e000abd"", ""de..."

In [10]:
# AS the null values are present only in 3 rows we will drop it 
movies = movies.dropna()

## processing string input into tags format

In [11]:
# these two attributes are in string format but we need it to be in dict format to extract name of genres 
print(type(movies['genres'][0]))
print(type(movies['keywords'][0]))

<class 'str'>
<class 'str'>

In [ ]:
## Converting movies names to lower case to make 
x = lambda a:a.lower()
movies['original_title'] = movies['original_title'].apply(x)

In [12]:
from ast import literal_eval

In [13]:
def conversion(x):
    array = np.array([])
    for i in literal_eval(x):
        array = np.append(array,i['name'])
    return array

In [14]:
movies['genres'] = movies['genres'].apply(conversion)
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
## Same process can be repeated for keywords as we are only interested in names

In [15]:
movies['keywords'] = movies['keywords'].apply(conversion)
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
# for cast we will take first 2 actors as they would be in lead roles of the movie

In [16]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [17]:
def conversion_cast(x):
    array = np.array([])
    count = 0

    for i in literal_eval(x):

        if count < 2:
            array = np.append(array, i['name'])
            count += 1

        if count == 2:
            break
    return array

In [18]:
movies['cast'] = movies['cast'].apply(conversion_cast)
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
def conversion_crew(x):
    
    for i in literal_eval(x):
        
        if (i['job']) == 'Director':
            return [i['name']]

In [20]:
movies['crew']  = movies['crew'].apply(conversion_crew)
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom]",[Gore Verbinski]
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine]",[Christopher Nolan]
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins]",[Andrew Stanton]

In [149]:
# Now converting owerview into list of words to get tags

In [21]:
splitting = lambda a:(a.split()) 
movies['overview'] = movies['overview'].apply(splitting)

In [22]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom]",[Gore Verbinski]
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine]",[Christopher Nolan]
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins]",[Andrew Stanton]

In [ ]:
# Removing spaces between words in each tag

In [23]:
def space_removal(x):
    l =[]
    for i in x:
        l.append(i.replace(" ",""))    
    return l

In [24]:
def space_removal_crew(x):
    l = []
    for i in x:            
        if type(i) != 'NoneType':
            l.append(i.replace(" ",""))
    return l

In [25]:
movies['cast'] = movies['cast'].apply(space_removal)
movies['genres'] = movies['genres'].apply(space_removal)
movies['keywords'] = movies['keywords'].apply(space_removal)

In [26]:
movies[movies['crew'].isna()]
# there are some na values in crew table so we are droping it

,movie_id,original_title,genres,keywords,overview,cast,crew
3669,19615,Flying By,"[[, {, "", i, d, "", :, , 1, 8, ,, , "", n, a, m,...",[],"[A, real, estate, developer, goes, to, his, 25...","[BillyRayCyrus, HeatherLocklear]",None
3678,447027,Running Forever,"[[, {, "", i, d, "", :, , 1, 0, 7, 5, 1, ,, , "",...",[],"[After, being, estranged, since, her, mother's...",[],None
3736,26379,Paa,"[[, {, "", i, d, "", :, , 1, 8, ,, , "", n, a, m,...",[],"[He, suffers, from, a, progeria, like, syndrom...","[AmitabhBachchan, AbhishekBachchan]",None
3984,55831,Boynton Beach Club,"[[, {, "", i, d, "", :, , 3, 5, ,, , "", n, a, m,...",[independentfilm],"[A, handful, of, men, and, women, of, a, certa...","[BrendaVaccaro, DyanCannon]",None
4075,371085,Sharkskin,"[[, ]]",[],"[The, Post, War, II, story, of, Manhattan, bor...",[],None
4112,48382,"The Book of Mormon Movie, Volume 1: The Journey","[[, ]]",[],"[The, story, of, Lehi, and, his, wife, Sariah,...","[KirbyHeyborne, MichaelFlynn]",None
4125,325140,Hum To Mohabbat Karega,"[[, ]]",[],"[Raju,, a, waiter,, is, in, love, with, the, f...",[],None
4130,20653,Roadside Romeo,"[[, {, "", i, d, "", :, , 1, 6, ,, , "", n, a, m,...",[],"[This, is, the, story, of, Romeo., A, dude, wh...","[SaifAliKhan, KareenaKapoor]",None
4254,361505,Me You and Five Bucks,"[[, {, "", i, d, "", :, , 1, 0, 7, 4, 9, ,, , "",...",[],"[A, womanizing, yet, lovable, loser,, Charlie,...",[],None
4311,114065,Down & Out With The Dolls,"[[, {, "", i, d, "", :, , 3, 5, ,, , "", n, a, m,...",[],"[The, raunchy,, spunky, tale, of, the, rise, a...",[],None
4320,137955,Crowsnest,"[[, ]]",[],"[In, late, summer, of, 2011,, five, young, fri...",[],None
4328,102840,Sex With Strangers,"[[, {, "", i, d, "", :, , 9, 9, ,, , "", n, a, m,...",[],"[For, some, married, couples,, sex, is, an, ob...",[],None
4380,47686,Dream with the Fishes,"[[, {, "", i, d, "", :, , 3, 5, ,, , "", n, a, m,...",[independentfilm],"[Terry, is, a, suicidal, voyeur, who, treats, ...","[DavidArquette, BradHunt]",None
4407,43630,The Helix... Loaded,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",[],[],[],None
4411,357441,Karachi se Lahore,"[[, {, "", i, d, "", :, , 1, 0, 7, 5, 1, ,, , "",...",[],"[A, road, trip, from, Karachi, to, Lahore, whe...","[ShehzadSheikh, AyeshaOmar]",None
4464,279759,Harrison Montgomery,"[[, ]]",[],"[Film, from, Daniel, Davila]",[],None
4510,331493,Light from the Darkroom,"[[, ]]",[],"[Light, in, the, Darkroom, is, the, story, of,...",[],None
4559,380097,America Is Still the Place,"[[, ]]",[],"[1971, post, civil, rights, San, Francisco, se...",[],None
4568,297100,The Little Ponderosa Zoo,"[[, ]]",[],"[The, Little, Ponderosa, Zoo, is, preparing, f...",[],None
4572,325579,Diamond Ruff,"[[, ]]",[],"[Action, -, Orphan,, con, artist,, crime, boss...",[],None
4577,328307,Rise of the Entrepreneur: The Search for a Bet...,"[[, ]]",[],"[The, world, is, changing, faster, than, ever....",[],None
4589,47546,I Want Your Money,"[[, {, "", i, d, "", :, , 9, 9, ,, , "", n, a, m,...",[],"[Two, versions, of, the, American, dream, now,...",[],None
4595,43743,Fabled,"[[, {, "", i, d, "", :, , 1, 8, ,, , "", n, a, m,...",[independentfilm],"[Joseph, just, broke, up, with, his, girlfrien...",[],None
4639,300327,Death Calls,"[[, ]]",[],"[An, action-packed, love, story, on, the, Mexi...",[],None
4644,378237,Amidst the Devil's Wings,"[[, {, "", i, d, "", :, , 1, 8, ,, , "", n, a, m,...",[],"[Prequel, to, ""5th, of, a, Degree.""]",[],None
4650,325123,Teeth and Blood,"[[, {, "", i, d, "", :, , 2, 7, ,, , "", n, a, m,...",[],"[A, beautiful, diva, is, murdered, on, the, se...","[GlennPlummer, MichelleVanDerWater]",None
4663,320435,UnDivided,"[[, ]]",[],"[UnDivided, documents, the, true, story, of, h...",[],None
4668,40963,Little Big Top,"[[, {, "", i, d, "", :, , 3, 5, ,, , "", n, a, m,...",[independentfilm],"[An, aging, out, of, work, clown, returns, to,...","[SidHaig, RichardRiehle]",None
4680,194588,Short Cut to Nirvana: Kumbh Mela,"[[, ]]",[],"[Every, 12, years, over, 70, million, pilgrims...",[],None
4722,38786,The Blood of My Brother: A Story of Death in Iraq,"[[, ]]",[],"[THE, BLOOD, OF, MY, BROTHER, goes, behind, th...",[],None

In [27]:
movies.dropna(inplace=True)
movies[movies['crew'].isna()]

Empty DataFrame
Columns: [movie_id, original_title, genres, keywords, overview, cast, crew]
Index: []

In [28]:
movies['crew'] = movies['crew'].apply(space_removal_crew)

In [ ]:
## Creating tags column

In [29]:
movies['tags'] = movies['overview'] + movies['keywords'] + movies['genres'] + movies['cast'] + movies['crew'] 
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [30]:
# removing comas and making it lower case 
movies['tags'] = movies['tags'].apply(lambda x:" ".join(x).lower())

In [31]:
movies = movies[['movie_id','original_title','tags']]
movies.head()

,movie_id,original_title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

### Text Processing of tags

In [32]:
from nltk.corpus import stopwords
from nltk import PorterStemmer

p = PorterStemmer()

In [129]:
#nltk.download('stopwords')

In [ ]:
## Removal of stopwords
## Steming of words so that tags like 'action' or 'actions' would become one tag

In [33]:
tags = movies['tags'].copy()
tags

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4776, dtype: object

In [34]:
i = 0
for sentence in tags:
    l = []
    for word in sentence.split():
        if word not in stopwords.words('english'):
            l.append(p.stem(word))

    movies['tags'][i] = ' '.join(l)
    i = i + 1

C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)

C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)

In [35]:
movies['tags']

0       22nd century, parapleg marin dispatch moon pan...
1       captain barbossa, long believ dead, come back ...
2       cryptic messag bond’ past send trail uncov sin...
3       follow death district attorney harvey dent, ba...
4       john carter war-weary, former militari captain...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4776, dtype: object

In [36]:
movies.head()

,movie_id,original_title,tags
0,19995,Avatar,"22nd century, parapleg marin dispatch moon pan..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ dead, come back ..."
2,206647,Spectre,cryptic messag bond’ past send trail uncov sin...
3,49026,The Dark Knight Rises,"follow death district attorney harvey dent, ba..."
4,49529,John Carter,"john carter war-weary, former militari captain..."

## Creating vectors using bag of words

In [37]:
from sklearn.feature_extraction import text

In [205]:
cv = text.CountVectorizer(max_features=10000)
vec = cv.fit_transform(movies['tags'])

In [206]:
vec = vec.toarray()

In [211]:
cv.get_feature_names()

['00',
 '000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '15th',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1863',
 '1890',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1927',
 '1930',
 '1930s',
 '1937',
 '1940',
 '1940s',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1986',
 '1987',
 '1990',
 '1994',
 '1995',
 '1996',
 '1997',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2007',
 '2008',
 '2009',
 '2012',
 '20th',
 '21st',
 '21stcenturi',
 '22nd',
 '23',
 '24',
 '25',
 '27',
 '28',
 '29',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '400',
 '47',
 '4th',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 '7th',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abbi',
 'abbiecornish',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abort',
 'abram',
 'abroad',
 'absolut',
 'absurd',
 'abus',
 'abuse',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acid',
 'acquaint',
 'acquir',
 'across',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'ada',
 'adam',
 'adammckay',
 'adams',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'addiction',
 'addit',
 'addl',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adolf',
 'adopt',
 'adoptivefath',
 'ador',
 'adrian',
 'adrianlyn',
 'adrienbrodi',
 'adrift',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'advantage',
 'adventur',
 'adventure',
 'adventures',
 'adversari',
 'advertis',
 'advic',
 'advice',
 'advis',
 'affair',
 'affect',
 'affection',
 'afflict',
 'affluent',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'afro',
 'after',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'afternoon',
 'ag',
 'again',
 'against',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'aggressionbyanim',
 'ago',
 'agre',
 'agrees',
 'ahead',
 'aid',
 'aidan',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airborn',
 'aircraft',
 'airforc',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'akshaykumar',
 'al',
 'alabama',
 'alan',
 'alaska',
 'alaskan',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcatraz',
 'alcohol',
 'alcoholabus',
 'aldou',
 'alec',
 'alecbaldwin',
 'alejandroamenábar',
 'alejandrogonzáleziñárritu',
 'alex',
 'alexanderpayn',
 'alexandreaja',
 'alexia',
 'alexisbledel',
 'alexkendrick',
 'alexpettyf',
 'alexproya',
 'alfi',
 'alfonsocuarón',
 'alfredhitchcock',
 'alfredmolina',
 'algeria',
 'ali',
 'alic',
 'alice',
 'aliciasilverston',
 'alien',
 'aliencontact',
 'alieninfect',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'alike',
 'aliv',
 'alive',
 'all',
 'alleg',
 'allegedli',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'allur',
 'almost',
 'alon',
 'alone',
 'along',
 'alongsid',
 'alp',
 'alpacino',
 'alpha',
 'alreadi',
 'also',
 'alt',
 'alter',
 'altern',
 'alternatedimens',
 'alternatehistori',
 'alternater',
 'although',
 'alvin',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amber',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'amelia',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanfootbal',
 'americanfootballplay',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'among',
 'amongst',
 'amor',
 'amount',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amyheckerl',
 'amysmart',
 'an',
 'ana',
 'anakin',
 'analyst',
 'analyz',
 'anandtuck',
 'anarchiccomedi',
 'anarchist',
 'anastasia',
 'anchor',
 'ancient',
 'ancientchina',
 'ancientegypt',
 'ancientgreec',
 'ancientrom',
 'ancientworld',
 'and',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewadamson',
 'andrewbujalski',
 'andrewdavi',
 'andrewflem',
 'andrewgarfield',
 'andrewniccol',
 'andrewstanton',
 'android',
 'andrzejbartkowiak',
 'andy',
 'andyfickman',
 'andygarcía',
 'andylau',
 'andysamberg',
 'andyserki',
 'andytenn',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'angels',
 'anger',
 'angle',
 'anglo',
 'angri',
 'angst',
 'anim',
 'animal',
 'animalattack',
 'animalhorror',
 'animallead',
 'animalprotect',
 'animals',
 'animalsidekick',
 'anjelicahuston',
 'ann',
 'anna',
 'annabel',
 'annafari',
 'annakendrick',
 'annapaquin',
 'annasophiarobb',
 'anne',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'annihil',
 'annihilation',
 'anniversari',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anonymouslett',
 'anoth',
 'another',
 'anotherdimens',
 'answer',
 'answers',
 'ant',
 'antarct',
 'antarctica',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthonyminghella',
 'anthonyrusso',
 'anthropomorph',
 'anti',
 'antic',
 'anticip',
 'antics',
 'antidot',
 'antihero',
 'antiqu',
 'antisemit',
 'antiterror',
 'antoinefuqua',
 'anton',
 'antoncorbijn',
 'antoni',
 'antonio',
 'antoniobandera',
 'antonyelchin',
 'anxieti',
 'anyon',
 'anyth',
 'anything',
 'anywher',
 'apart',
 'apartheid',
 'apartment',
 'apartments',
 'ape',
 'apes',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'apollo',
 'apostl',
 'appalachia',
 'appar',
 'appeal',
 'appear',
 'appears',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'arab',
 'arabian',
 'arbitrarylaw',
 'arch',
 'archaeolog',
 'archaeologist',
 'archenemi',
 'archeolog',
 'archeologist',
 'archer',
 'archeri',
 'architect',
 'archiv',
 'arctic',
 'arduou',
 'are',
 'area',
 'area51',
 'arena',
 'argentina',
 'argentinian',
 'argument',
 'aris',
 'aristocrat',
 'arizona',
 'ark',
 'arkansa',
 'arkin',
 'arlo',
 'arm',
 'armageddon',
 'armi',
 'armiehamm',
 'armor',
 'armoredcar',
 'arms',
 'armsdeal',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'around',
 'arrang',
 'arrangedmarriag',
 'arrangement',
 'array',
 'arrest',
 'arrested',
 'arriv',
 'arrival',
 'arrive',
 'arrives',
 'arrog',
 'arrow',
 'arson',
 'art',
 'artagnan',
 'artgalleri',
 'arthous',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialinsemin',
 'artificialintellig',
 'artist',
 'artists',
 'arts',
 'arttheft',
 'artthief',
 'as',
 'asabutterfield',
 'asgard',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashram',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'aspen',
 'asperger',
 'aspir',
 'aspirations',
 'aspiringsing',
 'ass',
 'assassin',
 'assassination',
 'assassinationattempt',
 'assassins',
 'assault',
 'assaultrifl',
 'assembl',
 'assert',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assort',
 'assum',
 'asteroid',
 'astonish',
 'astound',
 'astro',
 'astronaut',
 'astrophysicist',
 'asylum',
 'at',
 'atheist',
 'athlet',
 'atlant',
 'atlanta',
 'atlanticocean',
 'atom',
 'atomegoyan',
 'atomicbomb',
 'atroc',
 'attach',
 'attack',
 'attacks',
 'attempt',
 'attemptedmurd',
 'attemptedrap',
 'attempttoescap',
 'attend',
 'attent',
 'attention',
 'attic',
 'attitud',
 'attitude',
 'attorney',
 'attract',
 'attraction',
 'attractive',
 'auction',
 'audienc',
 'audiotap',
 'audit',
 'audition',
 'audrey',
 'audreyhepburn',
 'audreytaut',
 'august',
 'aunt',
 'auntniecerelationship',
 'aura',
 'austen',
 'austin',
 'australia',
 'australian',
 'australianoutback',
 'austria',
 'austrian',
 'author',
 'authorities',
 'authority',
 'autism',
 'autist',
 'auto',
 'autobiograph',
 'autobiographi',
 'autobot',
 'automat',
 'automaton',
 'automobilerac',
 'autoritianeduc',
 'autumn',
 'avail',
 'avatar',
 'aveng',
 'averag',
 'averil',
 'avert',
 'aviat',
 'aviv',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awe',
 'awesom',
 'awkward',
 'awol',
 'awri',
 'awry',
 'ax',
 'axe',
 'axel',
 'baader',
 'babe',
 'babi',
 'baby',
 'babysitt',
 'bachelor',
 'back',
 'backdrop',
 'background',
 'backgrounds',
 'backpack',
 'backstag',
 'backup',
 'backward',
 'backwat',
 'backwood',
 'backyard',
 'bad',
 'badboss',
 'badg',
 'badli',
 'badluck',
 'badmother',
 'bag',
 'bagoverhead',
 'bahama',
 'bahari',
 'bail',
 'bailey',
 'baker',
 'bakeri',
 'bakshi',
 'balanc',
 'balance',
 'balboa',
 'baldwin',
 'ball',
 'ballet',
 'balloon',
 'ballroom',
 'baltasarkormákur',
 'balthazar',
 'baltimor',
 'baltimore',
 'baltimoremaryland',
 'bammargera',
 'ban',
 'band',
 'bandit',
 'bandits',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bankrupt',
 'banner',
 'bannon',
 'bar',
 'barbara',
 'barbarian',
 'barber',
 'barbershop',
 'barbrastreisand',
 'barcelonaspain',
 'bare',
 'barfight',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barricad',
 'barrier',
 'barrio',
 'barry',
 'barrylevinson',
 'barrymore',
 'barrypepp',
 'barrysonnenfeld',
 'bars',
 'barsandrestaur',
 'bart',
 'bartend',
 'bartlett',
 'bas',
 'base',
 'basebal',
 'baseball',
 'baseballbat',
 'basedonarticl',
 'basedoncartoon',
 'basedonchildren',
 'basedoncomicbook',
 'basedoncomicstrip',
 'basedonfairytal',
 'basedonfilm',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonshortstori',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basket',
 'basketbal',
 'basketball',
 'bat',
 'bath',
 'bathhous',
 'bathori',
 'bathroom',
 'bathroomhumor',
 'bathtub',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battleassign',
 'battlefield',
 'battleforpow',
 'baxter',
 'bay',
 'bazluhrmann',
 'bdsm',
 'be',
 'beach',
 'beachhous',
 'beam',
 'bear',
 'beard',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beau',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becca',
 'becki',
 'beckon',
 'becom',
 'become',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'been',
 'beer',
 'beethoven',
 'befal',
 'before',
 'befriend',
 'beg',
 'began',
 'beggar',
 'begin',
 'begins',
 'beguil',
 'begun',
 'behavior',
 'behead',
 'behind',
 'beij',
 'being',
 'beirut',
 'belgium',
 'belief',
 'beliefs',
 'believ',
 'believe',
 'bell',
 'bella',
 'belong',
 'belongs',
 'belov',
 'beloved',
 'belt',
 'ben',
 'benaffleck',
 'benchaplin',
 'bend',
 'beneath',
 'benedict',
 'benedictcumberbatch',
 'benefactor',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benito',
 'benitomussolini',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennet',
 'bennett',
 'benstil',
 'bent',
 'benwheatley',
 'beret',
 'berlin',
 'berni',
 'berniemac',
 'besid',
 'besieg',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'bethani',
 'betray',
 'betrayal',
 'betrayals',
 'betroth',
 'bettemidl',
 'better',
 'betti',
 'bettythoma',
 'between',
 'beverli',
 'beverlyhil',
 'beyond',
 'bfg',
 'bi',
 'bia',
 'bianca',
 'bibl',
 'biblic',
 'bicker',
 'bicycl',
 'bid',
 'big',
 'bigfamili',
 'bigfoot',
 'bigger',
 'biggest',
 'bigotri',
 'bike',
 'biker',
 'bikini',
 'bilbo',
 'bill',
 'billard',
 'billcondon',
 'billewoodruff',
 'billhad',
 'billi',
 'billion',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'billythekid',
 'billywild',
 'billyzan',
 'bind',
 'binew',
 'bink',
 'binocular',
 'bio',
 'biograph',
 'biographi',
 'biohazard',
 'biolog',
 'biologicalweapon',
 'biologist',
 'biopic',
 'birch',
 'bird',
 'birde',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bitch',
 'bite',
 'bitten',
 'bitter',
 'bittersweet',
 'bizarr',
 'black',
 'blackandwhit',
 'blackbeard',
 'blackhol',
 'blackhumor',
 'blackmag',
 'blackmail',
 'blackmen',
 'blackout',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blake',
 'blakel',
 'blame',
 'blanchard',
 'bland',
 ...]

In [212]:
print(vec)
print('\n')
print(vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(4776, 10000)

In [ ]:
### In higher dimension Euclidean distance is not good so we will use Cosine Distance
### Cosine distance will gives us Theta, Smaller the theta the closer the other movie is to the 
### given movie and movie is very similar to given movie

In [213]:
from sklearn.metrics.pairwise import cosine_similarity

In [214]:
similarity_vec = cosine_similarity(vec)
similarity_vec

array([[1.        , 0.        , 0.02639818, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.02898855, ..., 0.01698089, 0.        ,
        0.        ],
       [0.02639818, 0.02898855, 1.        , ..., 0.01673655, 0.        ,
        0.        ],
       ...,
       [0.        , 0.01698089, 0.01673655, ..., 1.        , 0.36344868,
        0.2228006 ],
       [0.        , 0.        , 0.        , ..., 0.36344868, 1.        ,
        0.28392415],
       [0.        , 0.        , 0.        , ..., 0.2228006 , 0.28392415,
        1.        ]])

In [215]:
print(similarity_vec.shape)

(4776, 4776)

In [216]:
movies

,movie_id,original_title,tags
0,19995,avatar,"22nd century, parapleg marin dispatch moon pan..."
1,285,pirates of the caribbean: at world's end,"captain barbossa, long believ dead, come back ..."
2,206647,spectre,cryptic messag bond’ past send trail uncov sin...
3,49026,the dark knight rises,"follow death district attorney harvey dent, ba..."
4,49529,john carter,"john carter war-weary, former militari captain..."
...,...,...,...
4804,9367,el mariachi,el mariachi just wants to play his guitar and ...
4805,72766,newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"signed, sealed, delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,shanghai calling,when ambitious new york attorney sam is sent t...
4808,25975,my date with drew,ever since the second grade when he first saw ...

In [217]:
def similarity_of_movies(movie_name):
    movie_name = movie_name.lower()
    index = movies.loc[movies['original_title']==movie_name].index[0]
    
    movie_indexes = np.arange(0, similarity_vec[index].shape[0],
                         dtype='int').reshape(-1, 1)
    
    stack = np.hstack((similarity_vec[index].reshape(-1, 1),movie_indexes))
    
    sorted_stack = stack[stack[:,0].argsort()][::-1]
    
    similar_movies_index = sorted_stack[1:6][:,1]
    print(similar_movies_index)
    
    similar_movies = list(movies.iloc[similar_movies_index,1])
    
    return similar_movies

In [222]:
gg = similarity_of_movies('how to train your dragon')
gg

[ 160. 1309.  746. 2449.  803.]

['how to train your dragon 2',
 "dragon nest: warriors' dawn",
 'reign of fire',
 'chasseurs de dragons',
 'dragonheart']

In [168]:
movies.to_csv('Movies_with_Tags.csv')

In [223]:
import pickle 

pickle.dump(similarity_vec,open('similarity_vec','wb'))

In [224]:
pickle.load(open('similarity_vec','rb'))

array([[1.        , 0.        , 0.02639818, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.02898855, ..., 0.01698089, 0.        ,
        0.        ],
       [0.02639818, 0.02898855, 1.        , ..., 0.01673655, 0.        ,
        0.        ],
       ...,
       [0.        , 0.01698089, 0.01673655, ..., 1.        , 0.36344868,
        0.2228006 ],
       [0.        , 0.        , 0.        , ..., 0.36344868, 1.        ,
        0.28392415],
       [0.        , 0.        , 0.        , ..., 0.2228006 , 0.28392415,
        1.        ]])